package limeri.cards.model;

/**
 * A TrickCardPile contains groups of cards that are not in a hand.  This can be generated by meld or by tricks.
 */

import java.util.ArrayList;

import limeri.cards.Model;

public class TrickCardPile extends Model {
    private ArrayList <CardModel> cards;
    private ArrayList <ArrayList<CardModel>> trick;

    public ArrayList<CardModel> getCards() {return cards;}
    public void setCards(ArrayList<CardModel> cards) {this.cards = cards;}

    public ArrayList<ArrayList<CardModel>> getTrick() {return trick;}
    public void setTrick(ArrayList<ArrayList<CardModel>> trick) {this.trick = trick;}
}
